# Generated by Django 3.2 on 2023-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230511_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(blank=True, verbose_name='рейтинг на основе отзывов'),
        ),
    ]
