# Generated by Django 3.2 on 2023-05-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230512_1711'),
        ('core', '0010_alter_review_author'),
    ]

    operations = [
    ]
