# Generated by Django 3.2 on 2023-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20230512_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(verbose_name='описание произведения'),
        ),
    ]
