# Generated by Django 3.2 on 2023-05-12 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
