# Generated by Django 3.2 on 2023-05-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230513_0249'),
        ('core', '0013_comment_score'),
    ]

    operations = [
    ]
