# Generated by Django 3.2 on 2023-05-13 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["name"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="reviews.category",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(
                blank=True,
                validators=[django.core.validators.MaxValueValidator(2023)],
                verbose_name="год выпуска",
            ),
        ),
    ]
