# Generated by Django 3.2 on 2023-05-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230513_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
